/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.softcar.view;

import br.inatel.softcar.model.GerenteDAO;
import br.inatel.softcar.model.Usuario;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Brener
 */
public class CadastroGerente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroGerente
     */
    public CadastroGerente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        usuarioTexto = new javax.swing.JLabel();
        senhaTexto = new javax.swing.JLabel();
        jTextFieldGerenteUsuario = new javax.swing.JTextField();
        jTextFieldGerenteSenha = new javax.swing.JPasswordField();
        enderecoTexto = new javax.swing.JLabel();
        jTextFieldGerenteEmail = new javax.swing.JTextField();
        jTextFieldGerenteCodigoAcesso = new javax.swing.JPasswordField();
        senhaTexto1 = new javax.swing.JLabel();
        jButtonGerenteCadastrar = new javax.swing.JButton();
        jButtonGerenteVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        labelTitle.setText("Cadastro");

        usuarioTexto.setText("Nome de Usuário:");

        senhaTexto.setText("Senha:");

        jTextFieldGerenteUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGerenteUsuarioActionPerformed(evt);
            }
        });

        jTextFieldGerenteSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGerenteSenhaActionPerformed(evt);
            }
        });

        enderecoTexto.setText("Endereço de email:");

        jTextFieldGerenteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGerenteEmailActionPerformed(evt);
            }
        });

        jTextFieldGerenteCodigoAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGerenteCodigoAcessoActionPerformed(evt);
            }
        });

        senhaTexto1.setText("Codigo de Acesso:");

        jButtonGerenteCadastrar.setText("Cadastrar");
        jButtonGerenteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenteCadastrarActionPerformed(evt);
            }
        });

        jButtonGerenteVoltar.setText("Voltar");
        jButtonGerenteVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenteVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldGerenteCodigoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(usuarioTexto))
                            .addComponent(jTextFieldGerenteUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldGerenteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addComponent(senhaTexto)
                                    .addGap(95, 95, 95))
                                .addComponent(jTextFieldGerenteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(labelTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(enderecoTexto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonGerenteCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonGerenteVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(senhaTexto1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarioTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGerenteUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enderecoTexto)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldGerenteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(senhaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGerenteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(senhaTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGerenteCodigoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGerenteCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGerenteVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGerenteUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGerenteUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGerenteUsuarioActionPerformed

    private void jTextFieldGerenteSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGerenteSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGerenteSenhaActionPerformed

    private void jTextFieldGerenteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGerenteEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGerenteEmailActionPerformed

    private void jTextFieldGerenteCodigoAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGerenteCodigoAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGerenteCodigoAcessoActionPerformed

    private void jButtonGerenteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenteCadastrarActionPerformed
        String acesso = new String(jTextFieldGerenteCodigoAcesso.getPassword());
        if(acesso.equals("acessopermitido")) {
            Usuario u = new Usuario();
            GerenteDAO dao = new GerenteDAO();
            u.setNome(jTextFieldGerenteUsuario.getText());
            u.setEmail(jTextFieldGerenteEmail.getText());
            u.setSenha(Arrays.toString(jTextFieldGerenteSenha.getPassword()));
            dao.create(u);
        } else {
              JOptionPane.showMessageDialog(null, "Codigo de acesso incorreto.");
        }
        
    }//GEN-LAST:event_jButtonGerenteCadastrarActionPerformed

    private void jButtonGerenteVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenteVoltarActionPerformed
        TelaGerente tg = new TelaGerente();
        tg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonGerenteVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enderecoTexto;
    private javax.swing.JButton jButtonGerenteCadastrar;
    private javax.swing.JButton jButtonGerenteVoltar;
    private javax.swing.JPasswordField jTextFieldGerenteCodigoAcesso;
    private javax.swing.JTextField jTextFieldGerenteEmail;
    private javax.swing.JPasswordField jTextFieldGerenteSenha;
    private javax.swing.JTextField jTextFieldGerenteUsuario;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel senhaTexto;
    private javax.swing.JLabel senhaTexto1;
    private javax.swing.JLabel usuarioTexto;
    // End of variables declaration//GEN-END:variables
}
