/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.softcar.view;

import br.inatel.softcar.model.VagasDAO;
import java.util.ArrayList;
import javax.swing.ButtonGroup;

/**
 *
 * @author Brener
 */
public class TelaHomeGerente extends javax.swing.JFrame {

    /**
     * Creates new form TelaHomeGerente
     */
    public TelaHomeGerente(int id, String nome) {
        initComponents();
        jLabelNomeGerente.setText(nome);
        setLocationRelativeTo(null);
        carregarDadosVagas();
    }

    private TelaHomeGerente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void carregarDadosVagas() {
        ArrayList<Integer> listaVagas = new ArrayList();
        
        VagasDAO dao = new VagasDAO();
        listaVagas = dao.lerEstacionamento();
        
        if(listaVagas.get(0) == 1) {
            jRadioButton1.setSelected(true);
        }
        if(listaVagas.get(1) == 1) {
            jRadioButton2.setSelected(true);
        }
        if(listaVagas.get(2) == 1) {
            jRadioButton3.setSelected(true);
        }
        if(listaVagas.get(3) == 1) {
            jRadioButton4.setSelected(true);
        }
        if(listaVagas.get(4) == 1) {
            jRadioButton5.setSelected(true);
        }
        if(listaVagas.get(5) == 1) {
            jRadioButton6.setSelected(true);
        }
        if(listaVagas.get(6) == 1) {
            jRadioButton7.setSelected(true);
        }
        if(listaVagas.get(7) == 1) {
            jRadioButton8.setSelected(true);
        }
        if(listaVagas.get(8) == 1) {
            jRadioButton9.setSelected(true);
        }
        if(listaVagas.get(9) == 1) {
            jRadioButton10.setSelected(true);
        }
        if(listaVagas.get(10) == 1) {
            jRadioButton11.setSelected(true);
        }
        if(listaVagas.get(11) == 1) {
            jRadioButton12.setSelected(true);
        }
        if(listaVagas.get(0) == 0) {
            jRadioButton1.setSelected(false);
        }
        if(listaVagas.get(1) == 0) {
            jRadioButton2.setSelected(false);
        }
        if(listaVagas.get(2) == 0) {
            jRadioButton3.setSelected(false);
        }
        if(listaVagas.get(3) == 0) {
            jRadioButton4.setSelected(false);
        }
        if(listaVagas.get(4) == 0) {
            jRadioButton5.setSelected(false);
        }
        if(listaVagas.get(5) == 0) {
            jRadioButton6.setSelected(false);
        }
        if(listaVagas.get(6) == 0) {
            jRadioButton7.setSelected(false);
        }
        if(listaVagas.get(7) == 0) {
            jRadioButton8.setSelected(false);
        }
        if(listaVagas.get(8) == 0) {
            jRadioButton9.setSelected(false);
        }
        if(listaVagas.get(9) == 0) {
            jRadioButton10.setSelected(false);
        }
        if(listaVagas.get(10) == 0) {
            jRadioButton11.setSelected(false);
        }
        if(listaVagas.get(11) == 0) {
            jRadioButton12.setSelected(false);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOverviewEstacionamento = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jButtonBloquearVaga = new javax.swing.JButton();
        jButtonDesbloquearVaga = new javax.swing.JButton();
        jButtonSairGerente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNomeGerente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelOverviewEstacionamento.setPreferredSize(new java.awt.Dimension(700, 340));

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setText("jRadioButton3");

        jRadioButton4.setText("jRadioButton4");

        jRadioButton5.setText("jRadioButton5");

        jRadioButton6.setText("jRadioButton6");

        jRadioButton7.setText("jRadioButton7");

        jRadioButton8.setText("jRadioButton8");

        jRadioButton9.setText("jRadioButton9");

        jRadioButton10.setText("jRadioButton10");

        jRadioButton11.setText("jRadioButton11");

        jRadioButton12.setText("jRadioButton12");

        javax.swing.GroupLayout jPanelOverviewEstacionamentoLayout = new javax.swing.GroupLayout(jPanelOverviewEstacionamento);
        jPanelOverviewEstacionamento.setLayout(jPanelOverviewEstacionamentoLayout);
        jPanelOverviewEstacionamentoLayout.setHorizontalGroup(
            jPanelOverviewEstacionamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOverviewEstacionamentoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanelOverviewEstacionamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelOverviewEstacionamentoLayout.createSequentialGroup()
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton6))
                    .addGroup(jPanelOverviewEstacionamentoLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(58, 58, 58)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanelOverviewEstacionamentoLayout.createSequentialGroup()
                        .addComponent(jRadioButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton10)))
                .addGap(55, 55, 55)
                .addGroup(jPanelOverviewEstacionamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton11))
                .addGap(42, 42, 42)
                .addGroup(jPanelOverviewEstacionamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOverviewEstacionamentoLayout.setVerticalGroup(
            jPanelOverviewEstacionamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOverviewEstacionamentoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanelOverviewEstacionamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOverviewEstacionamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton11)
                        .addComponent(jRadioButton12))
                    .addGroup(jPanelOverviewEstacionamentoLayout.createSequentialGroup()
                        .addGroup(jPanelOverviewEstacionamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addGap(38, 38, 38)
                        .addGroup(jPanelOverviewEstacionamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8))
                        .addGap(46, 46, 46)
                        .addGroup(jPanelOverviewEstacionamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton10))))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jButtonBloquearVaga.setText("Bloquear Vaga");
        jButtonBloquearVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBloquearVagaActionPerformed(evt);
            }
        });

        jButtonDesbloquearVaga.setText("Desbloquear Vaga");

        jButtonSairGerente.setText("Sair");
        jButtonSairGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairGerenteActionPerformed(evt);
            }
        });

        jLabel1.setText("Mapa do Estacionamento");

        jLabel2.setText("Nome:");

        jLabelNomeGerente.setText("John");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelOverviewEstacionamento, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNomeGerente)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButtonBloquearVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButtonDesbloquearVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonSairGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelNomeGerente))
                .addGap(24, 24, 24)
                .addComponent(jPanelOverviewEstacionamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSairGerente)
                    .addComponent(jButtonDesbloquearVaga)
                    .addComponent(jButtonBloquearVaga))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBloquearVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBloquearVagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBloquearVagaActionPerformed

    private void jButtonSairGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairGerenteActionPerformed
        TelaInicial ti = new TelaInicial();
        ti.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSairGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHomeGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHomeGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHomeGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHomeGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHomeGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBloquearVaga;
    private javax.swing.JButton jButtonDesbloquearVaga;
    private javax.swing.JButton jButtonSairGerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNomeGerente;
    private javax.swing.JPanel jPanelOverviewEstacionamento;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
